# Generated by Django 3.2.3 on 2022-08-20 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
